### API de Usuarios
@baseUrl = http://localhost:3000
@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGUzNjM4MzJkOGJmMGM1NGFiMDY2MSIsImlhdCI6MTc3NjE3MDU4NiwiZXhwIjoxNzc2Nzc1Mzg2fQ.vqJLRQjMD05QiEYKutI7z3BZ5-aGgF_JxJgp0chIXps
@tokenAdmin = TOKEN_ADMIN_AQUI

### REGISTRO SIN FOTO (PRUEBA BÁSICA)
POST {{baseUrl}}/api/auth/registro
Content-Type: multipart/form-data; boundary=----123

------123
Content-Disposition: form-data; name="email"

test@gmail.com
------123
Content-Disposition: form-data; name="password"

123456
------123
Content-Disposition: form-data; name="nombre"

Test User
------123--


### REGISTRO CON FOTO (JSON)
POST {{baseUrl}}/api/auth/registro
Content-Type: application/json

{
  "email": "testfoto@gmail.com",
  "password": "123456",
  "nombre": "Test Con Foto"
}


### LOGIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joel@example.com",
  "password": "123456"
}


### ACTUALIZAR PERFIL (con archivo real)
PUT {{baseUrl}}/api/auth/perfil
Content-Type: multipart/form-data; boundary=----123
Authorization: Bearer {{tokenUser}}

------123
Content-Disposition: form-data; name="email"

nuevo.email@example.com
------123
Content-Disposition: form-data; name="password"

nueva123
------123
Content-Disposition: form-data; name="foto"; filename="foto.png"
Content-Type: image/png

< ./foto.png
------123--


### REGISTRO DUPLICADO (debe fallar)
POST {{baseUrl}}/api/auth/registro
Content-Type: multipart/form-data; boundary=----123

------123
Content-Disposition: form-data; name="email"

joel@example.com
------123
Content-Disposition: form-data; name="password"

otra123
------123
Content-Disposition: form-data; name="foto"; filename="foto.png"
Content-Type: image/png

< ./foto.png
------123--
